import Item from '../classes/Item';
import itemKeys from '../assets/json/itemKeys.json';
import STATS from './stats';
import TYPES from './types';
import POKEMONS from './pokemons';

const megaStonePokemonMap = {
  ABSOLITE: POKEMONS.ABSOL,
  ABOMASITE: POKEMONS.ABOMASNOW,
  AERODACTYLITE: POKEMONS.AERODACTYL,
  AGGRONITE: POKEMONS.AGGRON,
  ALAKAZITE: POKEMONS.ALAKAZAM,
  ALTARIANITE: POKEMONS.ALTARIA,
  AMPHAROSITE: POKEMONS.AMPHAROS,
  AUDINITE: POKEMONS.AUDINO,
  BANETTITE: POKEMONS.BANETTE,
  BEEDRILLITE: POKEMONS.BEEDRILL,
  BLASTOISINITE: POKEMONS.BLASTOISE,
  BLAZIKENITE: POKEMONS.BLAZIKEN,
  CAMERUPTITE: POKEMONS.CAMERUPT,
  CHARIZARDITE_X: POKEMONS.CHARIZARD,
  CHARIZARDITE_Y: POKEMONS.CHARIZARD,
  DIANCITE: POKEMONS.DIANCIE,
  GALLADITE: POKEMONS.GALLADE,
  GARCHOMPITE: POKEMONS.GARCHOMP,
  GARDEVOIRITE: POKEMONS.GARDEVOIR,
  GENGARITE: POKEMONS.GENGAR,
  GLALITITE: POKEMONS.GLALIE,
  GYARADOSITE: POKEMONS.GYARADOS,
  HERACROSSITE: POKEMONS.HERACROSS,
  HOUNDOOMITE: POKEMONS.HOUNDOOM,
  KANGASKHANITE: POKEMONS.KANGASKHAN,
  LATIASITE: POKEMONS.LATIAS,
  LATIOSITE: POKEMONS.LATIOS,
  LOPUNNITE: POKEMONS.LOPUNNY,
  LUCARIONITE: POKEMONS.LUCARIO,
  MANECTITE: POKEMONS.MANECTRIC,
  MAWILITE: POKEMONS.MAWILE,
  MEDICHAMITE: POKEMONS.MEDICHAM,
  METAGROSSITE: POKEMONS.METAGROSS,
  MEWTWONITE_X: POKEMONS.MEWTWO,
  MEWTWONITE_Y: POKEMONS.MEWTWO,
  PIDGEOTITE: POKEMONS.PIDGEOT,
  PINSIRITE: POKEMONS.PINSIR,
  SABLENITE: POKEMONS.SABLEYE,
  SALAMENCITE: POKEMONS.SALAMENCE,
  SCEPTILITE: POKEMONS.SCEPTILE,
  SCIZORITE: POKEMONS.SCIZOR,
  SHARPEDONITE: POKEMONS.SHARPEDO,
  SLOWBRONITE: POKEMONS.SLOWBRO,
  STEELIXITE: POKEMONS.STEELIX,
  SWAMPERTITE: POKEMONS.SWAMPERT,
  TYRANITARITE: POKEMONS.TYRANITAR,
  VENUSAURITE: POKEMONS.VENUSAUR
};
const itemBoostTypeMap = {
  DRACO_PLATE: TYPES.DRAGON,
  DRAGON_FANG: TYPES.DRAGON,
  DREAD_PLATE: TYPES.DARK,
  BLACK_GLASSES: TYPES.DARK,
  EARTH_PLATE: TYPES.GROUND,
  SOFT_SAND: TYPES.GROUND,
  FIST_PLATE: TYPES.FIGHTING,
  BLACK_BELT: TYPES.FIGHTING,
  FLAME_PLATE: TYPES.FIRE,
  CHARCOAL: TYPES.FIRE,
  ICICLE_PLATE: TYPES.ICE,
  NEVERMELT_ICE: TYPES.ICE,
  INSECT_PLATE: TYPES.BUG,
  SILVER_POWDER: TYPES.BUG,
  IRON_PLATE: TYPES.STEEL,
  METAL_COAT: TYPES.STEEL,
  MEADOW_PLATE: TYPES.GRASS,
  ROSE_INCENSE: TYPES.GRASS,
  MIRACLE_SEED: TYPES.GRASS,
  MIND_PLATE: TYPES.PSYCHIC,
  ODD_INCENSE: TYPES.PSYCHIC,
  TWISTED_SPOON: TYPES.PSYCHIC,
  PIXIE_PLATE: TYPES.FAIRY,
  SKY_PLATE: TYPES.FLYING,
  SHARP_BEAK: TYPES.FLYING,
  SPLASH_PLATE: TYPES.WATER,
  SEA_INCENSE: TYPES.WATER,
  WAVE_INCENSE: TYPES.WATER,
  MYSTIC_WATER: TYPES.WATER,
  SPOOKY_PLATE: TYPES.GHOST,
  SPELL_TAG: TYPES.GHOST,
  STONE_PLATE: TYPES.ROCK,
  ROCK_INCENSE: TYPES.ROCK,
  HARD_STONE: TYPES.ROCK,
  TOXIC_PLATE: TYPES.POISON,
  POISON_BARB: TYPES.POISON,
  ZAP_PLATE: TYPES.ELECTRIC,
  MAGNET: TYPES.ELECTRIC,
  SILK_SCARF: TYPES.NORMAL,
  PINK_BOW: TYPES.NORMAL,
  POLKADOT_BOW: TYPES.NORMAL
};
const itemResistTypeMap = {
  CHILAN_BERRY: TYPES.NORMAL,
  OCCA_BERRY: TYPES.FIRE,
  PASSHO_BERRY: TYPES.WATER,
  WACAN_BERRY: TYPES.ELECTRIC,
  RINDO_BERRY: TYPES.GRASS,
  YACHE_BERRY: TYPES.ICE,
  CHOPLE_BERRY: TYPES.FIGHTING,
  KEBIA_BERRY: TYPES.POISON,
  SHUCA_BERRY: TYPES.GROUND,
  COBA_BERRY: TYPES.FLYING,
  PAYAPA_BERRY: TYPES.PSYCHIC,
  TANGA_BERRY: TYPES.BUG,
  CHARTI_BERRY: TYPES.ROCK,
  KASIB_BERRY: TYPES.GHOST,
  HABAN_BERRY: TYPES.DRAGON,
  COLBUR_BERRY: TYPES.DARK,
  BABIRI_BERRY: TYPES.STEEL,
  ROSELI_BERRY: TYPES.FAIRY
};
const itemFlingPowerMap = {
  IRON_BALL: 130,
  HARD_STONE: 100,
  DEEP_SEA_TOOTH: 90,
  THICK_CLUB: 90,
  ASSAULT_VEST: 80,
  WEAKNESS_POLICY: 80,
  POISON_BARB: 70,
  DRAGON_FANG: 70,
  ADAMANT_ORB: 60,
  LUSTROUS_ORB: 60,
  MACHO_BRACE: 60,
  STICK: 60,
  SHARP_BEAK: 50,
  EVIOLITE: 40,
  BLACK_BELT: 30,
  BLACK_SLUDGE: 30,
  BLACK_GLASSES: 30,
  CHARCOAL: 30,
  DEEP_SEA_SCALE: 30,
  FLAME_ORB: 30,
  KINGS_ROCK: 30,
  LIFE_ORB: 30,
  LIGHT_BALL: 30,
  MAGNET: 30,
  METAL_COAT: 30,
  MIRACLE_SEED: 30,
  MYSTIC_WATER: 30,
  NEVERMELT_ICE: 30,
  RAZOR_FANG: 30,
  SOUL_DEW: 30,
  SPELL_TAG: 30,
  TOXIC_ORB: 30,
  TWISTED_SPOON: 30,
  AIR_BALLOON: 10,
  CHOICE_BAND: 10,
  CHOICE_SCARF: 10,
  CHOICE_SPECS: 10,
  DESTINY_KNOT: 10,
  ELECTRIC_SEED: 10,
  EXPERT_BELT: 10,
  FOCUS_BAND: 10,
  FOCUS_SASH: 10,
  GRASSY_SEED: 10,
  LAGGING_TAIL: 10,
  LEFTOVERS: 10,
  MENTAL_HERB: 10,
  METAL_POWDER: 10,
  MISTY_SEED: 10,
  MUSCLE_BAND: 10,
  POWER_HERB: 10,
  PSYCHIC_SEED: 10,
  QUICK_POWDER: 10,
  REAPER_CLOTH: 10,
  RED_CARD: 10,
  RING_TARGET: 10,
  SHED_SHELL: 10,
  SILK_SCARF: 10,
  SILVER_POWDER: 10,
  SMOOTH_ROCK: 10,
  SOFT_SAND: 10,
  SOOTHE_BELL: 10,
  WHITE_HERB: 10,
  WIDE_LENS: 10,
  WISE_GLASSES: 10,
  ZOOM_LENS: 10
};
const itemNaturalGiftMap = {
  APICOT_BERRY: {T: TYPES.GROUND, P: 100},
  BABIRI_BERRY: {T: TYPES.STEEL, P: 80},
  BELUE_BERRY: {T: TYPES.ELECTRIC, P: 100},
  CHARTI_BERRY: {T: TYPES.ROCK, P: 80},
  CHESTO_BERRY: {T: TYPES.WATER, P: 80},
  CHILAN_BERRY: {T: TYPES.NORMAL, P: 80},
  CHOPLE_BERRY: {T: TYPES.FIGHTING, P: 80},
  COBA_BERRY: {T: TYPES.FLYING, P: 80},
  COLBUR_BERRY: {T: TYPES.DARK, P: 80},
  CUSTAP_BERRY: {T: TYPES.GHOST, P: 100},
  DURIN_BERRY: {T: TYPES.WATER, P: 100},
  ENIGMA_BERRY: {T: TYPES.BUG, P: 100},
  GANLON_BERRY: {T: TYPES.ICE, P: 100},
  HABAN_BERRY: {T: TYPES.DRAGON, P: 80},
  JABOCA_BERRY: {T: TYPES.DRAGON, P: 100},
  KASIB_BERRY: {T: TYPES.GHOST, P: 80},
  KEBIA_BERRY: {T: TYPES.POISON, P: 80},
  KEE_BERRY: {T: TYPES.FAIRY, P: 100},
  LANSAT_BERRY: {T: TYPES.FLYING, P: 100},
  LEPPA_BERRY: {T: TYPES.FIGHTING, P: 80},
  LIECHI_BERRY: {T: TYPES.GRASS, P: 100},
  LUM_BERRY: {T: TYPES.FLYING, P: 80},
  MARANGA_BERRY: {T: TYPES.DARK, P: 100},
  MICLE_BERRY: {T: TYPES.ROCK, P: 100},
  OCCA_BERRY: {T: TYPES.FIRE, P: 80},
  ORAN_BERRY: {T: TYPES.POISON, P: 80},
  PASSHO_BERRY: {T: TYPES.WATER, P: 80},
  PAYAPA_BERRY: {T: TYPES.PSYCHIC, P: 80},
  PETAYA_BERRY: {T: TYPES.POISON, P: 100},
  RAWST_BERRY: {T: TYPES.GRASS, P: 80},
  RINDO_BERRY: {T: TYPES.GRASS, P: 80},
  ROSELI_BERRY: {T: TYPES.FAIRY, P: 80},
  ROWAP_BERRY: {T: TYPES.DARK, P: 100},
  SALAC_BERRY: {T: TYPES.FIGHTING, P: 100},
  SHUCA_BERRY: {T: TYPES.GROUND, P: 80},
  SITRUS_BERRY: {T: TYPES.PSYCHIC, P: 80},
  STARF_BERRY: {T: TYPES.PSYCHIC, P: 100},
  TANGA_BERRY: {T: TYPES.BUG, P: 80},
  WACAN_BERRY: {T: TYPES.ELECTRIC, P: 80},
  WATMEL_BERRY: {T: TYPES.FIRE, P: 100},
  YACHE_BERRY: {T: TYPES.ICE, P: 80}
};
const itemTechnoBlastMap = {BURN_DRIVE: TYPES.FIRE, CHILL_DRIVE: TYPES.ICE, DOUSE_DRIVE: TYPES.WATER, SHOCK_DRIVE: TYPES.ELECTRIC};
const itemMultiAttackMap = {
  FIGHTING_MEMORY: TYPES.FIGHTING,
  FLYING_MEMORY: TYPES.FLYING,
  POISON_MEMORY: TYPES.POISON,
  GROUND_MEMORY: TYPES.GROUND,
  ROCK_MEMORY: TYPES.ROCK,
  BUG_MEMORY: TYPES.BUG,
  GHOST_MEMORY: TYPES.GHOST,
  STEEL_MEMORY: TYPES.STEEL,
  FIRE_MEMORY: TYPES.FIRE,
  WATER_MEMORY: TYPES.WATER,
  GRASS_MEMORY: TYPES.GRASS,
  ELECTRIC_MEMORY: TYPES.ELECTRIC,
  PSYCHIC_MEMORY: TYPES.PSYCHIC,
  ICE_MEMORY: TYPES.ICE,
  DRAGON_MEMORY: TYPES.DRAGON,
  DARK_MEMORY: TYPES.DARK,
  FAIRY_MEMORY: TYPES.FAIRY
};
const itemBoostStatMap = {ELECTRIC_SEED: STATS.DF, GRASSY_SEED: STATS.DF, MISTY_SEED: STATS.SP, PSYCHIC_SEED: STATS.SP};
const getFlingPower = (key) => {
  const postfix = key.split('_')[1];

  if (postfix === 'PLATE') {
    return 90;
  }

  if (postfix === 'BERRY') {
    return 10;
  }

  return itemFlingPowerMap[key] || 0;
};

const ITEMS = {};
const items = new Array(294);
items.forEach((item, i) => {
  const key = itemKeys[i];

  items[i] = new Item({
    id: i,
    key,
    mega: megaStonePokemonMap[key],
    boostType: itemBoostTypeMap[key],
    resistType: itemResistTypeMap[key],
    flingPower: getFlingPower(key),
    naturalGiftPower: itemNaturalGiftMap[key] && itemNaturalGiftMap[key].p,
    naturalGiftType: itemNaturalGiftMap[key] && itemNaturalGiftMap[key].t,
    technoBlast: itemTechnoBlastMap[key],
    multiAttack: itemMultiAttackMap[key],
    boostedStat: itemBoostStatMap[key]
  });

  ITEMS[key] = items[i];
});

const ITEMS_GSC = items.slice(0, 30);
const ITEMS_ADV = items.slice(1, 80);
ITEMS_ADV.splice(8, 1);
ITEMS_ADV.splice(19, 1);
ITEMS_ADV.splice(21, 1);
const ITEMS_DPP = ITEMS_ADV.concat(items.slice(80, 149));
const ITEMS_BW = ITEMS_DPP.concat(items.slice(149, 176));
const ITEMS_XY = ITEMS_BW.concat(items.slice(176, 231));
const ITEMS_SM = ITEMS_XY.concat(items.slice(231));

export {ITEMS_GSC, ITEMS_ADV, ITEMS_DPP, ITEMS_BW, ITEMS_XY, ITEMS_SM, ITEMS};
